### ISSUE TITLE
Secret CODACY_PROJECT_TOKEN

### ISSUE THREAD

**Issue by tcurdt** [codacy/node-codacy-coverage#23]
I am a little confused on how the CODACY_PROJECT_TOKEN could be kept secret when integrating with a public CI server like travis-ci.

**Comment by rtfpessoa** [comment]
When using a public CI you must always use some mechanism like environment variables which are defined for each project in the admin panel and never commit this token to your repository.

**Comment by DavidTPate** [comment]
@tcurdt If you're using Travis-CI you can [encrypt the variables](https://docs.travis-ci.com/user/encryption-keys/) in your `.travis.yml` and they will be automatically decrypted for you on a build. 

Keep in mind that anyone with Write access to the Repo could view the keys if they wanted, and also the keys will not be used for PRs in a Fork (because they can't be decrypted), so if tests are dependent on the keys being there then it will fail.
