### ISSUE TITLE
Post-Commits Don't Work and Nothing is Shown on the Pull Requests Page

### ISSUE THREAD

**Issue by a11smiles** [codacy/node-codacy-coverage#33]
Exactly what the title says:

1. I've followed the instructions on the ["Setup GitHub" page](https://www.codacy.com/p/44684/settings/integrations) for setting up the web hook in GitHub.  I've yet to see Codacy show up in my post-commit checks.  I've checked on my Codacy webhook page in GitHub and it tells me that it's sending messages.

2. Nothing (no _Open Pull Requests_ or _Merged Pull Requests_) show up on the Pull Requests page in Codacy.  The page is completely empty.  What gives?

**Comment by pedrorijo91** [comment]
Hey @a11smiles ,

Sorry to hear about the problems you are facing integrating Codacy with your project. We'll have a look as fast as possible.

Nevertheless, this problem seems totally unrelated with this project, *node-codacy-coverage*, right ?
To get better response time, I would recommend you to contact us through our in-app support chat that should be visible inside our platform on the bottom right corner.

Thanks

**Comment by a11smiles** [comment]
@pedrorijo91 That's fantastic that you have an in-app support chat.  Unfortunately, I've not received a single response from the chat _yet_ and I've been waiting for two days.  So, I actually get better response time from GitHub.

**Comment by pedrorijo91** [comment]
I've notified the support team to check your issue asap. sorry for the delay. take into consideration that during weekends the support team may not be able to get back to you
